name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Composer dependencies
        working-directory: api
        run: |
          composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader
          chmod -R 775 storage
          chmod -R ugo+rw storage

      - name: Install NPM dependencies and build React
        working-directory: app
        env:
          VITE_API_URL: http://www.relationtrack.com/api
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Create deployment archive
        run: |
          zip -r relationtrack.zip api app/dist -x ".git/*" ".github/*" "api/vendor/*/test/*" "api/vendor/*/tests/*"

      - name: Copy archive to server and set permissions
        run: |
          echo "${{ secrets.SSH_KEY }}" > deploy_key
          chmod 600 deploy_key
          scp -i deploy_key -o StrictHostKeyChecking=no relationtrack.zip ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/
          ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            sudo unzip -o /tmp/relationtrack.zip -d /var/www/html/relationtrack
            sudo chown -R www-data:www-data /var/www/html/relationtrack
            sudo chmod -R 755 /var/www/html/relationtrack
            rm /tmp/relationtrack.zip
            cd /var/www/html/relationtrack/api
            sudo chown www-data:www-data /var/www/html/relationtrack/api/storage/logs/laravel.log
            sudo chmod 755 /var/www/html/relationtrack/api/storage/logs/laravel.log
            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan config:cache
            php artisan migrate
          EOF
          rm deploy_key
          rm relationtrack.zip
